name: 'cultivate'
version: '1.0.0'
config-version: 2

profile: 'cultivate'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  cultivate:
    metadata:
      +schema: metadata
      +materialized: view
    cultivate100:
      +schema: cultivate100
      staging:
        +materialized: view
      intermediate:
        +materialized: view
      marts:
        +materialized: table
    sharecity100:
      +schema: sharecity100
      staging:
        +materialized: view
      intermediate:
        +materialized: view
      marts:
        +materialized: table
