-- 01_file_formats.sql
-- File formats for JSON and CSV ingestion

CREATE OR REPLACE FILE FORMAT ff_json_strip_array
  TYPE = JSON
  STRIP_OUTER_ARRAY = TRUE;

CREATE OR REPLACE FILE FORMAT ff_csv_default
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL');

-- CSV format for ShareCity200 data (pre-deduplication)
CREATE OR REPLACE FILE FORMAT ff_csv_sharecity200
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  RECORD_DELIMITER = '\n'
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
  ENCODING = 'UTF8'
  EMPTY_FIELD_AS_NULL = TRUE;
