-- 05_transforms.sql
--
-- NOTE: This file is intentionally not used.
-- All data transformations are handled by dbt models in the /models directory.
--
-- The transformation pipeline is:
--   Raw tables (created by 03_create_tables.sql)
--   -> dbt staging models (/models/staging)
--   -> dbt intermediate models (/models/intermediate)
--   -> dbt marts (/models/marts)
--
-- To run transformations: dbt run
