-- 07_publish_for_bi.sql
-- Publish stable BI-facing views in a single schema for ThoughtSpot/Streamlit.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE FSI_WH;
USE DATABASE CULTIVATE;

CREATE SCHEMA IF NOT EXISTS BI_PRESENTATION;

CREATE OR REPLACE VIEW BI_PRESENTATION.V_MART_FSI_POWERBI_EXPORT AS
SELECT *
FROM HC_LOAD_DATA_FROM_CLOUD_MARTS.MART_FSI_POWERBI_EXPORT;

CREATE OR REPLACE VIEW BI_PRESENTATION.V_FSI_CITY_SUMMARY AS
SELECT *
FROM HC_LOAD_DATA_FROM_CLOUD_MARTS.FSI_CITY_SUMMARY;

CREATE OR REPLACE VIEW BI_PRESENTATION.V_FSI_CLUSTER_ANALYSIS AS
SELECT *
FROM HC_LOAD_DATA_FROM_CLOUD_MARTS.FSI_CLUSTER_ANALYSIS;

CREATE OR REPLACE VIEW BI_PRESENTATION.V_FSI_ACTIVITY_SUMMARY AS
SELECT *
FROM HC_LOAD_DATA_FROM_CLOUD_MARTS.FSI_ACTIVITY_SUMMARY;

CREATE OR REPLACE VIEW BI_PRESENTATION.V_FSI_DEDUPLICATION_IMPACT AS
SELECT *
FROM HC_LOAD_DATA_FROM_CLOUD_MARTS.FSI_DEDUPLICATION_IMPACT;
