-- ============================================================
-- 07: MART_FSI_POWERBI_EXPORT (Bronze/Raw)
-- Flat table for Power BI via ADF
-- Database: SNOWFLAKE_LEARNING_DB.PUBLIC
-- Source CSV: data/gold/mart_fsi_powerbi_export.csv
-- Generated by: infra/scripts/convert_gold_to_powerbi_csv.py
--
-- Usage:
--   First run  : Run all steps (1-5). Creates table + full load.
--   Incremental: Run steps 2-5 only. MERGE adds new records,
--                keeps existing date_checked for known IDs.
-- ============================================================

USE DATABASE SNOWFLAKE_LEARNING_DB;
USE SCHEMA PUBLIC;

-- 1. Create table IF NOT EXISTS (safe for incremental runs)
CREATE TABLE IF NOT EXISTS MART_FSI_POWERBI_EXPORT (
    id                      STRING,
    city                    STRING,
    country                 STRING,
    name                    STRING,
    url                     STRING,
    facebook_url            STRING,
    twitter_url             STRING,
    instagram_url           STRING,
    food_sharing_activities STRING,
    how_it_is_shared        STRING,
    date_checked            STRING,
    lat                     FLOAT,
    lon                     FLOAT,
    round                   STRING,
    growing                 INTEGER,
    distribution            INTEGER,
    cooking_eating          INTEGER,
    gifting                 INTEGER,
    collecting              INTEGER,
    selling                 INTEGER,
    bartering               INTEGER
);

-- 2. File format and internal stage
CREATE OR REPLACE FILE FORMAT powerbi_csv_format
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    ENCODING = 'UTF8'
    NULL_IF = ('');

CREATE OR REPLACE STAGE powerbi_export_stage
    FILE_FORMAT = powerbi_csv_format;

-- 3. Upload CSV to stage (overwrites previous staged file)
PUT file:///Users/hyunjicho/Documents/cultivate-mapping-pipeline/data/gold/mart_fsi_powerbi_export.csv
    @powerbi_export_stage AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- 4. MERGE: insert new records, preserve existing date_checked
MERGE INTO MART_FSI_POWERBI_EXPORT AS tgt
USING (
    SELECT
        $1  AS id,
        $2  AS city,
        $3  AS country,
        $4  AS name,
        $5  AS url,
        $6  AS facebook_url,
        $7  AS twitter_url,
        $8  AS instagram_url,
        $9  AS food_sharing_activities,
        $10 AS how_it_is_shared,
        $11 AS date_checked,
        $12 AS lat,
        $13 AS lon,
        $14 AS round,
        $15 AS growing,
        $16 AS distribution,
        $17 AS cooking_eating,
        $18 AS gifting,
        $19 AS collecting,
        $20 AS selling,
        $21 AS bartering
    FROM @powerbi_export_stage/mart_fsi_powerbi_export.csv
    (FILE_FORMAT => powerbi_csv_format)
) AS src
ON tgt.id = src.id
WHEN MATCHED THEN UPDATE SET
    tgt.city                    = src.city,
    tgt.country                 = src.country,
    tgt.name                    = src.name,
    tgt.url                     = src.url,
    tgt.facebook_url            = src.facebook_url,
    tgt.twitter_url             = src.twitter_url,
    tgt.instagram_url           = src.instagram_url,
    tgt.food_sharing_activities = src.food_sharing_activities,
    tgt.how_it_is_shared        = src.how_it_is_shared,
    -- date_checked: keep existing value (already preserved by Python script)
    tgt.date_checked            = tgt.date_checked,
    tgt.lat                     = src.lat,
    tgt.lon                     = src.lon,
    tgt.round                   = src.round,
    tgt.growing                 = src.growing,
    tgt.distribution            = src.distribution,
    tgt.cooking_eating          = src.cooking_eating,
    tgt.gifting                 = src.gifting,
    tgt.collecting              = src.collecting,
    tgt.selling                 = src.selling,
    tgt.bartering               = src.bartering
WHEN NOT MATCHED THEN INSERT (
    id, city, country, name, url,
    facebook_url, twitter_url, instagram_url,
    food_sharing_activities, how_it_is_shared,
    date_checked, lat, lon, round,
    growing, distribution, cooking_eating,
    gifting, collecting, selling, bartering
) VALUES (
    src.id, src.city, src.country, src.name, src.url,
    src.facebook_url, src.twitter_url, src.instagram_url,
    src.food_sharing_activities, src.how_it_is_shared,
    src.date_checked, src.lat, src.lon, src.round,
    src.growing, src.distribution, src.cooking_eating,
    src.gifting, src.collecting, src.selling, src.bartering
);

-- 5. Validate
SELECT COUNT(*) AS total_rows FROM MART_FSI_POWERBI_EXPORT;
SELECT
    COUNT(CASE WHEN date_checked IS NOT NULL THEN 1 END) AS has_date,
    COUNT(CASE WHEN date_checked IS NULL THEN 1 END)     AS no_date
FROM MART_FSI_POWERBI_EXPORT;
SELECT * FROM MART_FSI_POWERBI_EXPORT LIMIT 5;
